services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - "8080:8080"       # HTTP доступ
      - "50000:50000"     # JNLP для агентов
      - "8443:8443"       # HTTPS порт Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins-keystore.jks:/var/jenkins_home/jenkins-keystore.jks:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jenkins-keystore.jks --httpsKeyStorePassword=password
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  nginx:
    image: nginx:alpine
    container_name: jenkins-nginx
    restart: unless-stopped
    ports:
      - "443:443"         # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - jenkins

volumes:
  jenkins_home:
