version: '3'
services:
  web1:
    build: ./web1
    ports:
      - "8081:80"

  web2:
    build: ./web2
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  haproxy:
    image: haproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
